branch-defaults:
  master:
    environment: impactme
global:
  application_name: social_marketing
  default_ec2_keyname: webserver
  default_platform: Ruby 2.2 (Passenger Standalone)
  default_region: us-east-1
  profile: eb-cli
  sc: git
